#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var schema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var model = db.model("test1", schema );



model.find({},null,{limit:2},function(err,docs){
    console.log(docs);
});


model.find({},null,{skip:4},function(err,docs){
    console.log(docs);
});


model.find({},{name:1, age:1, _id:0},{sort:{age:1}},function(err,docs){
  console.log(docs);
});
