#!/usr/local/bin/node

var mongoose = require('mongoose')


var db = mongoose.connect("mongodb://127.0.0.1:27017/test")

db.connection.on('error', function(error){
        console.log('error'+ error)
})

db.connection.on("open", function(){
        console.log('connection success!')
})


var tschema = new mongoose.Schema({
	name: {type: String},
	age: {type: Number, default: 18},
	gender: {type: Boolean, default: true}
})


var tmodel= db.model("tdoc", tschema);


