#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var schema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var model = db.model("test1", schema );





model.find({"age":{"$gt":18}},function(error,docs){
   //查询所有nage大于18的数据
});
 
model.find({"age":{"$lt":60}},function(error,docs){
   //查询所有nage小于60的数据
});
 
model.find({"age":{"$gte":18,"$lt":60}},function(error,docs){
   //查询所有nage大于等18小于60的数据
});


model.find({name:{$ne:'test4'}, age: {$lt:27}},function(err,docs){
	console.log(docs);
})


model.find({ age:{ $in: 20}},function(error,docs){
   //查询age等于20的所有数据
});
 
 
model.find({ age:{$in:[20,30]}},function(error,docs){
  //可以把多个值组织成一个数组
}); 

model.find({"$or":[{"name":"yaya"},{"age":28}]},function(error,docs){
  //查询name为yaya或age为28的全部文档
});


model.find({name: {$exists: true}},function(error,docs){
  //查询所有存在name属性的文档
});
 
model.find({telephone: {$exists: false}},function(error,docs){
  //查询所有不存在telephone属性的文档
});
