#!/usr/local/bin/node

var mongoose = require('mongoose')
var db = mongoose.connect("mongodb://192.168.1.200:27017/test")

db.connection.on('error', function(error){
	console.log('error'+ error)
})

db.connection.on("open", function(){
	console.log('connection success!')
})

console.log(db)
