#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var schema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var model = db.model("test1", schema );

var condition = {name:'jerry'};

var update = {$set:{age:16}};
model.update(condition, update, function(error, docs){
	console.log(docs);
	model.find({}, function(err, doc){
        	console.log(doc);
	})

})


