#!/usr/local/bin/node

var express = require('express');
var cookieParser = require('cookie-parser');

var app = express()
app.use(cookieParser);

app.get('*', function(req, res){
	console.log('come')
	if(req.cookies.isVisit){
		res.send('first')
	}else{
		res.cookie('isVisit', 1, {maxAge: 60*1000});
		res.send('again');
	}
});


app.listen(9999)
