#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");

var mongoose = require('mongoose');

var schema = new mongoose.Schema;
schema.add({ name: 'String', email: 'String', age: 'Number' });


schema.method('say', function(){
	console.log('help');
})


var say = mongoose.model('say', schema);

var lenka = new say();
lenka.say();
