#!/usr/local/bin/node

var express = require('express');

var session = require('express-session');

var app = express();

app.use(session({
	secret: 'asd',
	cookie: {
		maxAge: 60 * 1000 * 30
	}
}));

app.get('/', function(req, res){
	if(req.session.sign){
		console.log(req.session);
		res.send('session name :'+ req.session.name);
	}else{
		req.session.sign = true;
		req.session.name = 'sss';
		res.send('welcome');
	}
});


app.listen(9999)
