#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var TestSchema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var TestModel = db.model("test1", TestSchema );
var TestEntity = new TestModel({
    name : "jerry", 
    age  : 28, 
    email: "jerry@qq.com"
});
TestEntity.save(function(error,doc) {
   console.log(doc);
});


var entity1 = new TestModel({
	name:'lgj',
	age:10,
	email:'a@A'
});

entity1.save(function(err, doc){
	console.log(doc)
})
