#!/usr/local/bin/node	

var path = require('path');
var data1 = path.basename('/usr/local/projects/moojnn.com');
var data2 = path.basename('/usr/local/projects/moojnn.com', 'com');
var data3 = path.basename('/usr/local/projects/moojnn.com', 'n.com');

console.log(data1);
console.log(data2);
console.log(data3);
