#!/usr/local/bin/node

var util = require('util');
var result = util.format('%s:%s', 'foo');
console.log(result);



var r1 = util.format('%s:%s', 'foo', 'bar', 'baz');
console.log(r1);


var r2 = util.format(1,2,3,4);
console.log(r2);
