#!/usr/local/bin/node

var mongoose = require('mongoose');

var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var schema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var model = db.model("test1", schema );





model.find({"age":{"$gt":18}},function(error,docs){
   //查询所有nage大于18的数据
});
 
model.find({"age":{"$lt":60}},function(error,docs){
   //查询所有nage小于60的数据
});
 
model.find({"age":{"$gte":18,"$lt":60}},function(error,docs){
   //查询所有nage大于等18小于60的数据
});
