#!/usr/local/bin/node


var mongoose = require("mongoose");
var db = mongoose.connect("mongodb://127.0.0.1:27017/test");
var TestSchema = new mongoose.Schema({
    name : { type:String },
    age  : { type:Number, default:0 },
    email: { type:String },
    time : { type:Date, default:Date.now }
});
var TestModel = db.model("test1", TestSchema );


TestModel.create({name:"lgj", age:30}, function(err, docs){
	console.log(docs);
})

TestModel.find({},function(error,  docs){
	console.log("@@@@@@@@@");
	console.log(docs);
})
