#!/usr/local/bin/node
var url = require('url');
var src = url.format({
	protocol:'https:',
	hostname: 'baidu.com',
	port: 90,
	pathname : '/news',
	query: {
		page:1,
		id:22,
		name:33
	}
});
console.log(src);
