var fw = require('./file')(require('fs'));
var data = require('./static');
var mtd = require('./factory')(data);
require('./student')(fw, data, mtd);
require('./course')(fw, data, mtd);
//require('./teacher')(fw, data, mtd);
//require('./internet')(fw, data, mtd);
//require('./concat')(fw, data, mtd);
//require('./onecard')(fw, data, mtd);
//require('./club')(fw, data, mtd);
//require('./guihua')(fw, data, mtd);
//require('./jijian')(fw, data, mtd);
//require('./chuqin')(fw, data, mtd);
//require('./duty')(fw, data, mtd);
console.log('done');