#!/usr/local/bin/node

var express = require('express');
var app = express();

app.all('*', function(request,response,next){
	response.writeHead(200, {"Content-Type": "text/html;chartset=utf-8"});
	next();
});

app.get("/", function(request,response){
	response.end("welcome to homepage!");
});

app.get("/about", function(request, response){
	response.end("welcome to about!");
});


app.get("*", function(request, response){
	response.end("404 -not found!");
});

app.listen(9999);
